// <auto-generated />
using System;
using DengueAlert.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DengueAlert.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029183224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DengueAlert.Api.Models.DengueAlerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("CasProv")
                        .HasColumnType("int");

                    b.Property<int?>("Casos")
                        .HasColumnType("int");

                    b.Property<double?>("CasosEst")
                        .HasColumnType("double");

                    b.Property<double?>("CasosEstMax")
                        .HasColumnType("double");

                    b.Property<double?>("CasosEstMin")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIniSE")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EndWeek")
                        .HasColumnType("int");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<int>("GeoCode")
                        .HasColumnType("int");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<int?>("NivelInc")
                        .HasColumnType("int");

                    b.Property<int?>("NotifAccumYear")
                        .HasColumnType("int");

                    b.Property<double?>("PInc100k")
                        .HasColumnType("double");

                    b.Property<double?>("PRt1")
                        .HasColumnType("double");

                    b.Property<int?>("Pop")
                        .HasColumnType("int");

                    b.Property<int?>("Receptivo")
                        .HasColumnType("int");

                    b.Property<double?>("Rt")
                        .HasColumnType("double");

                    b.Property<int>("SemanaEpidemiologica")
                        .HasColumnType("int");

                    b.Property<double?>("TempMax")
                        .HasColumnType("double");

                    b.Property<double?>("TempMed")
                        .HasColumnType("double");

                    b.Property<double?>("TempMin")
                        .HasColumnType("double");

                    b.Property<int?>("Transmissao")
                        .HasColumnType("int");

                    b.Property<double?>("UmidMax")
                        .HasColumnType("double");

                    b.Property<double?>("UmidMed")
                        .HasColumnType("double");

                    b.Property<double?>("UmidMin")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VersaoModelo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EndWeek", "EndYear", "GeoCode")
                        .IsUnique();

                    b.ToTable("DengueAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
